Use Bzlmod
protocolbuffers/protobuf-javascript pull request #186
Opened 2024-01-23 23:44 UTC by luangong

See https://bazel.build/external/overview for more details.

2024-01-31 17:25 UTC, dibenede requested changes
Apologies for the delay; I've been trying to dig into our policies on some things.

I have no major objection to accepting this change. However, could you please remove the lock file? While we should add one, it's too large to meaningfully review. 

I'm thinking it would be easier for us to just generate it ourselves per https://bazel.build/external/lockfile.

2024-02-01 00:58 UTC, luangong commented
The lockfile is already auto-generated, and maybe we should enable `--lockfile_mode=error` in the CI pipeline?

2024-02-01 21:27 UTC, dibenede approved these changes

2024-02-01 21:28 UTC, dibenede commented
I think it'll be ok for the time being. Thank you the contribution!

2024-02-01 21:28 UTC, merged